# =================================================== #
# Configuration options for DataFumblerMVAuto.
# DataFumblerAuto will attempt load this file for
# default before overriding.
# =================================================== #


[OobaSampling]

# =========================== #
# Prompts to translate each and every type.
events = "BEGINNING OF CONVERSATION: Avoid repetition, do not ever loop. Always stay in character. Translates all actions in full, elaborate, explicit, graphic, and vivid detail. You are an expert Smut translator who translates Japanese text.\n\nTranslate all text into English and output it in the following format. Reply with exactly only the English Translation of the text.\n\n\n***\n\nUSER: {dialogue}</s>\nASSISTANT:"

map_names = "BEGINNING OF CONVERSATION: Reply with only the english translation of the location name\n\n\n***\n\nUSER: {dialogue}</s>\nASSISTANT:"

items = "BEGINNING OF CONVERSATION: Reply with only the english translation of the RPG item name and Description in 2 seperate sentences.\n\n\n***\n\nUSER: {dialogue}</s>\nASSISTANT:"

actors = "BEGINNING OF CONVERSATION: Reply with only the english translation of the NPC name.\n\n\n***\n\nUSER: {dialogue}</s>\nASSISTANT:"

armors = "BEGINNING OF CONVERSATION: Reply with only the english translation of the RPG equipment name.\n\n\n***\n\nUSER: {dialogue}</s>\nASSISTANT:"
classes = "BEGINNING OF CONVERSATION: Reply with only the english translation of the RPG class name.\n\n\n***\n\nUSER: {dialogue}</s>\nASSISTANT:"
weapons = "BEGINNING OF CONVERSATION: Reply with only the english translation of the RPG weapon name.\n\n\n***\n\nUSER: {dialogue}</s>\nASSISTANT:"

# =========================== #

# The url to send the request to.
ooba_url = "http://localhost:5000/api/v1/generate"



# Temperature. This makes the model more wild for higher values or tamer/stricter for lower values.
temp = 0.9
# Top P Sampling. Determines the Probability range to consider "words"
top_p = 0.2
top_k = 0

preset = "None"
do_sample = true

# Similar to "Frequency Penalty" provided in OpenAI.
# 1.0 Means "No penalty" while higher values means the model will try to avoid
repetition_penalty = 1.0
# Range on 
repetition_penalty_range = 1024

# Seed. Setting it to the same will generation across different runs will be the same
seed = -1

# Add Bos token... You should't be fiddling with it unless you know what it does.
add_bos_token = false

max_new_tokens = 1024
auto_max_new_tokens = true
stopping_strings = ["</s>"]

# Mirostat allows linguistic models to generate high quality text without
# the need to manually adjust parameters
# These tweaks the k in the "top-k" above.
# 
mirostat_mode = 2
mirostat_tau = 5
mirostat_eta = 0.1

[OpenAISampling]
# ==================================== #
# API key for OpenAI. reads from the file called "local.txt"
# ==================================== #
# DO NOT SHARE THIS API KEY!
# ==================================== #
# Unless you're generous, do not share
# the API key as other people will
# have access to it!
# ==================================== #
API_Key = "file local.txt"

# The system prompt to use for events
events = "You are an expert translator who translates Japanese text into natural english. You are to translate with verbantism. While translating you are allowed to rewrite sentences to fit the dialogue better."

# Prompt taken from DazedMTLTool. Thank you for your service.
map_names = "Reply with only the english translation of the location name"

items = "Reply with only the english translation of the RPG item name and Description in 2 seperate sentences."

actors = "Reply with only the english translation of the NPC name."

armors = "Reply with only the english translation of the RPG equipment name"
classes = "Reply with only the english translation of the RPG class name"
weapons = "Reply with only the english translation of the RPG weapon name"


# Temperature. This makes the model more wild for higher values or tamer/stricter for lower values.
# 0.0 means
temp = 0.0

# Higher frequency penalty > More repetition
frequency_penalty = 0.2
# common or cliché phrases
presence_penalty = 0.2
model = "gpt-3.5-turbo"

[Google]

# Collapses Event new lines. Example:
# [こころ]
# こにちは
# わたしはこころです！

# [こころ]
# こにちは わたしはこころです！

# For google, always collapse newlines. and unexpand them later
# Punctuations to detect on collapsing or not
# empty means do not collapse.
punctuations = "？！。…」♡♥、"

[MTool]

# "MTool" Translator....
# It isn't a really good translator.
# Sure it's auto but the translation it produces...
# Frankly sucks.

# Skip lines where MTool falls it's face flat:
# - Skip unbalanced braced lines
# - Skip Multiple punctuations
# - Test if the translation is way too short
#   for the original line by a factor of 1.5
# If the value is empty or not found, defaults to true.
skip_undesirables = true