# =================================================== #
# Default Configuration options for DataFumbler.
# =================================================== #

[General]
# Replace existing files in the "translations folder" folder when mapping?
replace = false

# Defines the game "type". Generally, if you see "www" folder together with "game.exe", it is "MV" game. If you see "data" together with "game.exe", it's a "MZ" game.
type = "MV"

# Configs relating to System.json mapping.
[System]
# Map equipTypes?
armor_types = true
# Map equipTypes?
equip_types = true
# Map elements?
elements = true
# Map skillTypes?
skill_types = true

# Terms stuff
# Export Terms?
# May not be the same across games!
# Recommended to export.
terms = true

# Applies some default translations used in
# the english version of RPGMakerMV. 
terms_map_default = true


# Unsupported Arguments

# Map "switches"?
# This can potentially break some games as
# it is typically not shown to the player.
switches = false

# Map "variables" (aka map variable names)?
# This can potentially break some games as
# it is typically not shown to the player.
# Useful for code_122. See below.
variables = false

# Change the locale for the System.json.
# Untested & not implemented. May break things.
locale = false

[Events]

# Process D_Text variables.
# if `DTextPicture.js` is inside the plugins folder, do consider enable this.
# By default is enabled as disabling it doesn't have any negative effects.
dtext = true

# Automatically if a string value is detected in code_122, it will automatically get added.
# Since this only checks for strings, it should be fine to leave it "true"/Enabled.
# This may over capture things. Use with caution.
auto_code_122 = false
# Use this to block certain variables from being translated.
black_code_122 = []
# If any game uses `\v[number]` inside map.json or commonevents.json, consider noting down the number inside it and write it down to translate it properly.
# This additionally checks for string elements and skips integers.
code_122 = []
